library friendzone_flutter.globals;

import 'package:flutter/material.dart';
import 'package:friendzone_flutter/db_comm/friendzone_exceptions.dart';
import 'package:friendzone_flutter/models/current_user.dart';
import 'package:friendzone_flutter/pages/login_page/login.dart';

CurrentUser? activeUser;

const Color friendzoneYellow = Color.fromARGB(255, 255, 204, 0);

/// Display a snackbar at the bottom of the screen with the given [message]
/// Need to provide a [context] for rendering purposes
void makeSnackbar(BuildContext context, String message) {
  ScaffoldMessenger.of(context).clearSnackBars();
  ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(message)));
}

/// Handle the types of errors that can be generated by PHP calls. Will display
/// a snackbar on a PHP or general error, and kick user back to the login page
/// on a token exception
void unifiedErrorCatch(BuildContext context, Exception e) {
  if (e is TokenException) {
    ScaffoldMessenger.of(context).clearSnackBars();
    activeUser = null;
    Navigator.pushReplacement(
        context,
        MaterialPageRoute(
            builder: ((context) => const LoginPage(tokenLogout: true))));
  } else {
    makeSnackbar(context, e.toString());
  }
}
